### PR TITLE
fix(isEmpty): Ignore empty strings on list iteration.

### PR DESCRIPTION
**Pull request by themihai**
Initially submitted to https://github.com/hoisie/mustache/pull/37

### CODE REVIEW

**Comment by cbroglie** [comment]
Thanks @themihai, could you include a test case which demonstrates the behavior change?

**Comment by themihai** [comment]
As this is part of the spec I thought this is already covered by the mustache compliance tests suite. Let me know if it's not the case.

**Comment by cbroglie** [comment]
If there is a spec test for this then it's currently one of the disabled ones (see https://github.com/cbroglie/mustache/blob/master/spec_test.go#L12). Enabling a spec test which was previously failing but is now passing with your change would be even better than a new standalone test.

**Comment by vvakame** [comment]
any update?
I want to make same changes. but I found this PR. I need this changes.

**Comment by cbroglie** [comment]
I wrote a test for this in 214307b9 which confirms the behavior change. I looked through https://github.com/mustache/spec/blob/master/specs/sections.yml but didn't see an explicit test case.

**Pull request merged**
