### PR TITLE
Multiple Readme badges and codecov integration

### PR DESCRIPTION
**Pull request by kishaningithub**

### CODE REVIEW

**Comment by cbroglie** [comment]
Thanks @kishaningithub. Unfortunately it looks like this change has broken some of the CI builds.

**Comment by kishaningithub** [comment]
@cbroglie Checks are green now :-)

**Comment by kishaningithub** [comment]
Hi @cbroglie Any comments ?

**Comment by cbroglie** [comment]
Looks good, thank you

**Pull request merged**
